version: '3.9'

services:
  php7.1:
    image: php:7.1.3-fpm
    build:
      context: ./php7.1
    hostname: php7.1
    ports:
      - "10001:9000"
    volumes:
      - ../Projects/:/var/www/html/
      - ./php7.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php7.1/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php7.3:
    image: php:7.3-fpm
    build:
      context: ./php7.3
    hostname: php7.3
    ports:
      - "10002:9000"
    volumes:
      - ../Projects/:/var/www/html/
      - ./php7.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php7.3/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php7.4:
    image: php:7.4-fpm
    build:
      context: ./php7.4
    hostname: php7.4
    ports:
      - "10003:9000"
    volumes:
      - ../Projects/:/var/www/html/
      - ./php7.4/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php7.4/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php8:
    #image: php:8-fpm
    build:
      context: ./php8
    hostname: php8
    ports:
      - "10004:9000"
    volumes:
      - ../Projects/:/var/www/html/
      - ./php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php8/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php8.2:
    build:
      context: ./php8.2
    hostname: php8.2
    ports:
      - "10005:9000"
    volumes:
      - ../Projects/:/var/www/html/
      - ./php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php8.2/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ../Projects/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7.1
      - php7.3
      - php7.4
      - php8
      - php8.2
    networks:
      - backend
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - backend
  redis:
    image: arm64v8/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/:/data
    networks:
      - backend
  redisui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - "7843:7843"
    volumes:
      - ./p3x-redis-ui-settings:/settings
    networks:
      - backend
  elastic:
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - elastic_container=true
    networks:
      - backend
networks:
  backend:
    driver: bridge